In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)
#import geopandas
import tensorflow
import keras
from keras.models import Model
from keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from keras.optimizers import RMSprop
#from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
#from keras.utils import to_categorical
from keras.callbacks import EarlyStopping
from sklearn.preprocessing import StandardScaler
import numpy as np
import math
import sklearn.metrics
from sklearn.model_selection import train_test_split
from tensorflow.keras.optimizers import Adam

In [ ]:
from google.colab import auth
auth.authenticate_user()

In [ ]:
import ee
ee.Authenticate()
ee.Initialize(project='geewildfires')

T4 GPU works well without costing a lot, L100 faster but expensive

In [ ]:
def open_file(gcs_path):
    #lnglat = None
    #full_file = '/vsigs/jk_wildfiresspreadts/' + gcs_path
    full_file = 'gs://jk_wildfiresspreadts/' + gcs_path
    df = pd.read_csv(full_file)
    return df

In [ ]:
fires_df = open_file("FINAL_PartFourOutput_WUI.csv")
fires_df.head()

,Unnamed: 0,FIRE_ID,UrbanAngle,occur_id,point_id,IsUrban,WUIBreach,Month,NDVI,NDWI,NBR,DEM,aspect,hillshade,slope,bi,erc,eto,fm100,fm1000,pr,rmax,rmin,th,pop_density,tmmn,tmmx,vpd,vs,LandCover,Y,Water,Very_low_rural,Low_density_rural,Rural_cluster,Suburban,Semi_dense_urban,Dense_urban,Urban_centre,first_urban_point,RemoveFlag
0,202,NV4091811770219850817,-52.270315,2,0,0,0,8,0.056068,0.105315,-0.133341,1580.415405,215.0,195.0,8.0,-0.000004,59.422588,6.077752,6.004851,8.000117,0.76846,39.612396,12.523386,37.000031,0.0,285.6987,303.04364,2.164311,2.565506,71,1,0,1,0,0,0,0,0,0,99,False
1,203,NV4091811770219850817,-52.270315,2,1,0,0,8,0.060680,0.103729,-0.121322,1580.415405,215.0,195.0,8.0,-0.000004,59.422588,6.077752,6.004851,8.000117,0.76846,39.612396,12.523386,37.000031,0.0,285.6987,303.04364,2.164311,2.565506,71,1,0,1,0,0,0,0,0,0,99,False
2,204,NV4091811770219850817,-52.270315,2,2,0,0,8,0.060265,0.100935,-0.134430,1578.098389,276.0,189.0,3.0,-0.000004,59.422588,6.077752,6.004851,8.000117,0.76846,39.612396,12.523386,37.000031,0.0,285.6987,303.04364,2.164311,2.565506,71,1,0,1,0,0,0,0,0,0,99,False
3,205,NV4091811770219850817,-52.270315,2,3,0,0,8,0.056502,0.098674,-0.140869,1575.750000,269.0,189.0,3.0,-0.000004,59.422588,6.077752,6.004851,8.000117,0.76846,39.612396,12.523386,37.000031,0.0,285.6987,303.04364,2.164311,2.565506,71,1,0,1,0,0,0,0,0,0,99,False
4,206,NV4091811770219850817,-52.270315,2,4,0,0,8,0.065172,0.102284,-0.157150,1575.750000,269.0,189.0,3.0,-0.000004,59.422588,6.077752,6.004851,8.000117,0.76846,39.612396,12.523386,37.000031,0.0,285.6987,303.04364,2.164311,2.565506,71,1,0,1,0,0,0,0,0,0,99,False

In [ ]:
print(fires_df.info(verbose=True, show_counts=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1369333 entries, 0 to 1369332
Data columns (total 41 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Unnamed: 0         1369333 non-null  int64
 1   FIRE_ID            1369333 non-null  object
 2   UrbanAngle         1369333 non-null  float64
 3   occur_id           1369333 non-null  int64
 4   point_id           1369333 non-null  int64
 5   IsUrban            1369333 non-null  int64
 6   WUIBreach          1369333 non-null  int64
 7   Month              1369333 non-null  int64
 8   NDVI               1369333 non-null  float64
 9   NDWI               1369333 non-null  float64
 10  NBR                1369333 non-null  float64
 11  DEM                1369333 non-null  float64
 12  aspect             1369333 non-null  float64
 13  hillshade          1369333 non-null  float64
 14  slope              1369333 non-null  float64
 15  bi                 1369333 non-null  float64
 16  erc                1369333 non-null  float64
 17  eto                1369333 non-null  float64
 18  fm100              1369333 non-null  float64
 19  fm1000             1369333 non-null  float64
 20  pr                 1369333 non-null  float64
 21  rmax               1369333 non-null  float64
 22  rmin               1369333 non-null  float64
 23  th                 1369333 non-null  float64
 24  pop_density        1369333 non-null  float64
 25  tmmn               1369333 non-null  float64
 26  tmmx               1369333 non-null  float64
 27  vpd                1369333 non-null  float64
 28  vs                 1369333 non-null  float64
 29  LandCover          1369333 non-null  int64
 30  Y                  1369333 non-null  int64
 31  Water              1369333 non-null  int64
 32  Very_low_rural     1369333 non-null  int64
 33  Low_density_rural  1369333 non-null  int64
 34  Rural_cluster      1369333 non-null  int64
 35  Suburban           1369333 non-null  int64
 36  Semi_dense_urban   1369333 non-null  int64
 37  Dense_urban        1369333 non-null  int64
 38  Urban_centre       1369333 non-null  int64
 39  first_urban_point  1369333 non-null  int64
 40  RemoveFlag         1369333 non-null  bool
dtypes: bool(1), float64(22), int64(17), object(1)
memory usage: 419.2+ MB
None

In [ ]:
fires = fires_df.drop(columns=["Unnamed: 0"])
fires.head(50)

,FIRE_ID,UrbanAngle,occur_id,point_id,IsUrban,WUIBreach,Month,NDVI,NDWI,NBR,DEM,aspect,hillshade,slope,bi,erc,eto,fm100,fm1000,pr,rmax,rmin,th,pop_density,tmmn,tmmx,vpd,vs,LandCover,Y,Water,Very_low_rural,Low_density_rural,Rural_cluster,Suburban,Semi_dense_urban,Dense_urban,Urban_centre,first_urban_point,RemoveFlag
0,NV4091811770219850817,-52.270315,2,0,0,0,8,0.056068,0.105315,-0.133341,1580.415405,215.0,195.0,8.0,-0.000004,59.422588,6.077752,6.004851,8.000117,0.768460,39.612396,12.523386,37.000031,0.0,285.698700,303.043640,2.164311,2.565506,71,1,0,1,0,0,0,0,0,0,99,False
1,NV4091811770219850817,-52.270315,2,1,0,0,8,0.060680,0.103729,-0.121322,1580.415405,215.0,195.0,8.0,-0.000004,59.422588,6.077752,6.004851,8.000117,0.768460,39.612396,12.523386,37.000031,0.0,285.698700,303.043640,2.164311,2.565506,71,1,0,1,0,0,0,0,0,0,99,False
2,NV4091811770219850817,-52.270315,2,2,0,0,8,0.060265,0.100935,-0.134430,1578.098389,276.0,189.0,3.0,-0.000004,59.422588,6.077752,6.004851,8.000117,0.768460,39.612396,12.523386,37.000031,0.0,285.698700,303.043640,2.164311,2.565506,71,1,0,1,0,0,0,0,0,0,99,False
3,NV4091811770219850817,-52.270315,2,3,0,0,8,0.056502,0.098674,-0.140869,1575.750000,269.0,189.0,3.0,-0.000004,59.422588,6.077752,6.004851,8.000117,0.768460,39.612396,12.523386,37.000031,0.0,285.698700,303.043640,2.164311,2.565506,71,1,0,1,0,0,0,0,0,0,99,False
4,NV4091811770219850817,-52.270315,2,4,0,0,8,0.065172,0.102284,-0.157150,1575.750000,269.0,189.0,3.0,-0.000004,59.422588,6.077752,6.004851,8.000117,0.768460,39.612396,12.523386,37.000031,0.0,285.698700,303.043640,2.164311,2.565506,71,1,0,1,0,0,0,0,0,0,99,False
5,NV4091811770219850817,-52.270315,2,5,0,0,8,0.061031,0.097288,-0.157150,1569.649536,317.0,190.0,5.0,-0.000004,59.422588,6.077752,6.004851,8.000117,0.768460,39.612396,12.523386,37.000031,0.0,285.698700,303.043640,2.164311,2.565506,71,1,0,1,0,0,0,0,0,0,99,False
6,NV4091811770219850817,-52.270315,2,6,0,0,8,0.065087,0.103098,-0.152231,1569.649536,317.0,190.0,5.0,-0.000004,63.949570,6.403963,5.500517,7.037678,0.522566,38.585674,10.066293,37.000031,0.0,285.359467,305.917786,2.564676,2.497403,71,1,0,1,0,0,0,0,0,0,99,False
7,NV4091811770219850817,-52.270315,2,7,0,0,8,0.054541,0.095758,-0.182467,1566.874756,308.0,191.0,4.0,-0.000004,63.949570,6.403963,5.500517,7.037678,0.522566,38.585674,10.066293,37.000031,0.0,285.359467,305.917786,2.564676,2.497403,71,1,0,1,0,0,0,0,0,0,99,False
8,NV4091811770219850817,-52.270315,2,8,0,0,8,0.053248,0.089074,-0.198369,1544.093262,3.0,178.0,13.0,-0.000004,63.949570,6.403963,5.500517,7.037678,0.522566,38.585674,10.066293,37.000031,0.0,285.359467,305.917786,2.564676,2.497403,71,1,0,1,0,0,0,0,0,0,99,False
9,NV4091811770219850817,-52.270315,2,9,0,0,8,0.063477,0.092551,-0.163862,1544.093262,3.0,178.0,13.0,-0.000004,63.949570,6.403963,5.500517,7.037678,0.522566,38.585674,10.066293,37.000031,0.0,285.359467,305.917786,2.564676,2.497403,71,1,0,1,0,0,0,0,0,0,99,False
10,NV4091811770219850817,-52.270315,2,10,0,0,8,0.063978,0.100608,-0.151661,1545.501465,358.0,182.0,12.0,-0.000004,63.949570,6.403963,5.500517,7.037678,0.522566,38.585674,10.066293,37.000031,0.0,285.359467,305.917786,2.564676,2.497403,71,1,0,1,0,0,0,0,0,0,99,False
11,NV4091811770219850817,-52.270315,2,11,0,0,8,0.050325,0.089619,-0.130877,1529.760254,7.0,176.0,12.0,-0.000004,63.949570,6.403963,5.500517,7.037678,0.522566,38.585674,10.066293,37.000031,0.0,285.359467,305.917786,2.564676,2.497403,71,1,0,1,0,0,0,0,0,0,99,False
12,NV4091811770219850817,-52.270315,2,12,0,0,8,0.073817,0.114188,-0.057535,1524.288086,320.0,207.0,13.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
13,NV4091811770219850817,-52.270315,2,13,0,0,8,0.060387,0.095987,-0.107022,1524.288086,320.0,207.0,13.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
14,NV4091811770219850817,-52.270315,2,14,0,0,8,0.050592,0.089004,-0.133270,1519.222290,166.0,171.0,13.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
15,NV4091811770219850817,-52.270315,2,15,0,0,8,0.044461,0.083312,-0.117031,1527.860352,158.0,162.0,16.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
16,NV4091811770219850817,-52.270315,2,16,0,0,8,0.056620,0.093916,-0.124666,1527.860352,158.0,162.0,16.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
17,NV4091811770219850817,-52.270315,2,17,0,0,8,0.064205,0.105505,-0.133270,1541.088257,211.0,189.0,6.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
18,NV4091811770219850817,-52.270315,2,18,0,0,8,0.054476,0.096918,-0.133260,1541.088257,211.0,189.0,6.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
19,NV4091811770219850817,-52.270315,2,19,0,0,8,0.059461,0.100839,-0.130941,1536.327271,243.0,204.0,8.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
20,NV4091811770219850817,-52.270315,2,20,0,0,8,0.059356,0.090563,-0.139193,1528.778076,222.0,197.0,8.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
21,NV4091811770219850817,-52.270315,2,21,0,0,8,0.059356,0.101768,-0.139193,1528.778076,222.0,197.0,8.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
22,NV4091811770219850817,-52.270315,2,22,0,0,8,0.058631,0.099524,-0.151394,1524.396118,211.0,197.0,10.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
23,NV4091811770219850817,-52.270315,2,23,0,0,8,0.052948,0.085150,-0.145903,1513.693604,351.0,190.0,19.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
24,NV4091811770219850817,-52.270315,2,24,0,0,8,0.053428,0.083729,-0.104693,1510.927979,0.0,181.0,18.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,1,0,1,0,0,0,0,0,0,99,False
25,NV4091811770219850817,-52.270315,2,25,0,0,8,0.049672,0.086620,-0.084813,1510.927979,0.0,181.0,18.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
26,NV4091811770219850817,-52.270315,2,26,0,0,8,0.064478,0.098577,-0.064341,1484.276489,4.0,177.0,16.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
27,NV4091811770219850817,-52.270315,2,27,0,0,8,0.069232,0.106847,-0.046693,1487.142456,5.0,175.0,20.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
28,NV4091811770219850817,-52.270315,2,28,0,0,8,0.082583,0.116573,-0.029954,1487.142456,5.0,175.0,20.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
29,NV4091811770219850817,-52.270315,2,29,0,0,8,0.056503,0.094953,-0.041777,1472.278320,219.0,204.0,12.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
30,NV4091811770219850817,-52.270315,2,30,0,0,8,0.069456,0.114797,-0.025211,1472.278320,219.0,204.0,12.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
31,NV4091811770219850817,-52.270315,2,31,0,0,8,0.065208,0.109640,-0.037392,1460.718994,274.0,192.0,4.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
32,NV4091811770219850817,-52.270315,2,32,0,0,8,0.060834,0.110546,-0.041777,1463.226074,227.0,208.0,12.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
33,NV4091811770219850817,-52.270315,2,33,0,0,8,0.065122,0.115842,-0.033703,1463.226074,227.0,208.0,12.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
34,NV4091811770219850817,-52.270315,2,34,0,0,8,0.060675,0.106133,-0.042231,1452.735474,325.0,187.0,4.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
35,NV4091811770219850817,-52.270315,2,35,0,0,8,0.065001,0.111435,-0.042231,1465.600830,262.0,216.0,12.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
36,NV4091811770219850817,-52.270315,2,36,0,0,8,0.082563,0.136309,0.004392,1456.444458,260.0,216.0,12.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
37,NV4091811770219850817,-52.270315,2,37,0,0,8,0.082530,0.135218,-0.004116,1454.271606,265.0,206.0,8.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
38,NV4091811770219850817,-52.270315,2,38,0,0,8,0.078103,0.130834,-0.027812,1447.227661,253.0,205.0,8.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
39,NV4091811770219850817,-52.270315,2,39,0,0,8,0.078095,0.137894,-0.026967,1438.572632,274.0,189.0,3.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
40,NV4091811770219850817,-52.270315,2,40,0,0,8,0.069667,0.122488,-0.028430,1448.903076,274.0,211.0,10.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
41,NV4091811770219850817,-52.270315,2,41,0,0,8,0.073863,0.128731,-0.008226,1440.257690,278.0,211.0,10.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
42,NV4091811770219850817,-52.270315,2,42,0,0,8,0.078166,0.130898,-0.016927,1440.257690,278.0,211.0,10.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
43,NV4091811770219850817,-52.270315,2,43,0,0,8,0.091233,0.128731,-0.024690,1424.630737,318.0,190.0,4.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
44,NV4091811770219850817,-52.270315,2,44,0,0,8,0.082698,0.122184,-0.042228,1423.466797,333.0,185.0,4.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
45,NV4091811770219850817,-52.270315,2,45,0,0,8,0.082739,0.127684,-0.029952,1423.466797,333.0,185.0,4.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
46,NV4091811770219850817,-52.270315,2,46,0,0,8,0.069480,0.121310,-0.041775,1410.935913,337.0,185.0,4.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
47,NV4091811770219850817,-52.270315,2,47,0,0,8,0.078177,0.124580,-0.037047,1410.935913,337.0,185.0,4.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
48,NV4091811770219850817,-52.270315,2,48,0,0,8,0.069533,0.125687,-0.045366,1409.704346,342.0,185.0,4.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False
49,NV4091811770219850817,-52.270315,2,49,0,0,8,0.082537,0.123662,-0.040555,1405.396973,304.0,187.0,3.0,60.043880,84.467041,6.427491,5.468115,7.027750,0.384250,40.334675,9.441586,37.000031,0.0,284.077484,306.198303,2.582191,2.477189,71,0,0,1,0,0,0,0,0,0,99,False

In [ ]:
# Initial order:
# 1. count sequence lengths and number of sequences (create_sequences_for_training)
# 2. drop column names (create_sequences_for_training)
# 2. split into X and Y as lists of sequences (create_sequences_for_training)
# 3. split into train and test (using the lists - count lists, take first 66% as train) (split_train_test)
# 4. convert from df to np array (.values)
# 5. concatenate all values in the X training array (train_scaler)
# 6. .fit the StandardScaler on those values (train_scaler)
# 7. .transform all the X values per sequence using the new scaler object (normalise X) (scaler_transform)
# 8. pad sequences (sequence.pad_sequences)
# 9. reshape for keras

# Order changed again later - train / test split done on FIRE_ID, then lists of sequences created

In [ ]:
def create_fire_id_groups(df):
    fire_groups = df.groupby('FIRE_ID')
    fire_list = []
    for fidx, fseq in fire_groups:
        fire_list.append(fseq)
    return fire_list

def create_sequences_from_fire_ids(list_of_fires):
    no_sequences = 0
    max_seq = 0
    min_seq = 100
    longest_id = 0
    X_list = []
    Y_list = []
    for df in list_of_fires:
      df_groups = df.groupby('occur_id')
      for idx, seq in df_groups:
          seq_len = len(seq)
          no_sequences += 1
          if seq_len > max_seq:
              max_seq = seq_len
              longest_id = seq["occur_id"].iloc[0]
          if seq_len < min_seq:
              min_seq = seq_len

          Y = seq["Y"]
          Y_list.append(Y)
          X = seq.drop(columns=["LandCover", "WUIBreach", "Month", "first_urban_point", "RemoveFlag"])#.values
          X_list.append(X)

    return no_sequences, max_seq, min_seq, longest_id, X_list, Y_list

In [ ]:
def create_sequences_from_fire_ids_twice(list_of_fires):
    import gc
    no_sequences = 0
    max_seq = 0
    min_seq = 100
    longest_id = 0
    X_list = []
    Y_list = []
    for df in list_of_fires:

      df_odd = df[df['point_id'] % 2 != 0]
      df = df[df['point_id'] % 2 != 1]

      for idx, seq in df_odd.groupby('occur_id'):
          seq_len = len(seq)
          no_sequences += 1
          if seq_len > max_seq:
              max_seq = seq_len
              longest_id = seq["occur_id"].iloc[0]
          if seq_len < min_seq:
              min_seq = seq_len

          Y = seq["Y"]
          Y_list.append(Y)
          X = seq.drop(columns=["LandCover", "WUIBreach", "Month", "first_urban_point", "RemoveFlag"])
          X_list.append(X)

      for idx, seq in df.groupby('occur_id'):
            seq_len = len(seq)
            no_sequences += 1
            if seq_len > max_seq:
                max_seq = seq_len
                longest_id = seq["occur_id"].iloc[0]
            if seq_len < min_seq:
                min_seq = seq_len

            Y = seq["Y"]
            Y_list.append(Y)
            X = seq.drop(columns=["LandCover", "WUIBreach", "Month", "first_urban_point", "RemoveFlag"])
            X_list.append(X)

    return no_sequences, max_seq, min_seq, longest_id, X_list, Y_list

In [ ]:
def create_sequences_for_training(df):
    df_groups = df.groupby('occur_id')
    no_sequences = 0
    max_seq = 0
    min_seq = 100
    longest_id = 0
    X_list = []
    Y_list = []
    for idx, seq in df_groups:
        seq_len = len(seq)
        no_sequences += 1
        if seq_len > max_seq:
            max_seq = seq_len
            longest_id = seq["occur_id"].iloc[0]
        if seq_len < min_seq:
            min_seq = seq_len

        Y = seq["Y"]
        Y_list.append(Y)
        X = seq.drop(columns=["LandCover", "WUIBreach", "Month", "first_urban_point", "RemoveFlag"])
        X_list.append(X)

    return no_sequences, max_seq, min_seq, longest_id, X_list, Y_list

In [ ]:
def train_scaler(X_list):
    import copy
    scaler = StandardScaler()
    X_list_copy = copy.deepcopy(X_list)
    for X_sequence in X_list_copy:
        X_sequence = X_sequence.drop(columns=["IsUrban", "occur_id", "point_id", "Y", "FIRE_ID"], inplace=True)
    X_concat = np.concatenate(X_list_copy)
    scaler.fit(X_concat)
    return scaler

In [ ]:
def scaler_transform(X_list, scaler):
    new_Xlist = []
    for X_sequence in X_list:
        X_sequence.drop(columns=["IsUrban", "occur_id", "point_id", "Y", "FIRE_ID"], inplace=True)
        X_values = X_sequence.values
        X_norm = scaler.transform(X_values)
        new_Xlist.append(X_norm)
    return new_Xlist

In [ ]:
all_fires_list = create_fire_id_groups(fires)
X_train_list, X_test_list = train_test_split(all_fires_list, test_size=0.3, train_size=0.7, random_state=19, shuffle=True, stratify=None)

In [ ]:
print(f"Training fires: {len(X_train_list)}")
print(f"Testing fires: {len(X_test_list)}")

Training fires: 1560
Testing fires: 669

In [ ]:
_, steps, _, _, X_train, Y_train = create_sequences_from_fire_ids_twice(X_train_list)
_, _, _, _, X_test, Y_test = create_sequences_from_fire_ids_twice(X_test_list)

In [ ]:
print(X_train[0])

                      FIRE_ID  UrbanAngle  occur_id  point_id  IsUrban  \
399743  CA3443711869619880903   62.778349      3521         1        0
399745  CA3443711869619880903   62.778349      3521         3        0
399747  CA3443711869619880903   62.778349      3521         5        0
399749  CA3443711869619880903   62.778349      3521         7        0
399751  CA3443711869619880903   62.778349      3521         9        0
399753  CA3443711869619880903   62.778349      3521        11        0
399755  CA3443711869619880903   62.778349      3521        13        0
399757  CA3443711869619880903   62.778349      3521        15        0
399759  CA3443711869619880903   62.778349      3521        17        0
399761  CA3443711869619880903   62.778349      3521        19        0
399763  CA3443711869619880903   62.778349      3521        21        0
399765  CA3443711869619880903   62.778349      3521        23        0
399767  CA3443711869619880903   62.778349      3521        25        0
399769  CA3443711869619880903   62.778349      3521        27        0
399771  CA3443711869619880903   62.778349      3521        29        0
399773  CA3443711869619880903   62.778349      3521        31        0
399775  CA3443711869619880903   62.778349      3521        33        0
399777  CA3443711869619880903   62.778349      3521        35        0
399779  CA3443711869619880903   62.778349      3521        37        0
399781  CA3443711869619880903   62.778349      3521        39        0
399783  CA3443711869619880903   62.778349      3521        41        0
399785  CA3443711869619880903   62.778349      3521        43        0
399787  CA3443711869619880903   62.778349      3521        45        0
399789  CA3443711869619880903   62.778349      3521        47        0
399791  CA3443711869619880903   62.778349      3521        49        0
399793  CA3443711869619880903   62.778349      3521        51        1
399795  CA3443711869619880903   62.778349      3521        53        1
399797  CA3443711869619880903   62.778349      3521        55        0
399799  CA3443711869619880903   62.778349      3521        57        0
399801  CA3443711869619880903   62.778349      3521        59        0
399803  CA3443711869619880903   62.778349      3521        61        0
399805  CA3443711869619880903   62.778349      3521        63        0
399807  CA3443711869619880903   62.778349      3521        65        0
399809  CA3443711869619880903   62.778349      3521        67        0
399811  CA3443711869619880903   62.778349      3521        69        0
399813  CA3443711869619880903   62.778349      3521        71        1
399815  CA3443711869619880903   62.778349      3521        73        0
399817  CA3443711869619880903   62.778349      3521        75        0
399819  CA3443711869619880903   62.778349      3521        77        0
399821  CA3443711869619880903   62.778349      3521        79        0
399823  CA3443711869619880903   62.778349      3521        81        0
399825  CA3443711869619880903   62.778349      3521        83        0
399827  CA3443711869619880903   62.778349      3521        85        0
399829  CA3443711869619880903   62.778349      3521        87        0
399831  CA3443711869619880903   62.778349      3521        89        0
399833  CA3443711869619880903   62.778349      3521        91        0
399835  CA3443711869619880903   62.778349      3521        93        0
399837  CA3443711869619880903   62.778349      3521        95        0
399839  CA3443711869619880903   62.778349      3521        97        0
399841  CA3443711869619880903   62.778349      3521        99        0
399843  CA3443711869619880903   62.778349      3521       101        0
399845  CA3443711869619880903   62.778349      3521       103        1
399847  CA3443711869619880903   62.778349      3521       105        1
399849  CA3443711869619880903   62.778349      3521       107        1

            NDVI      NDWI       NBR         DEM  aspect  hillshade  slope  \
399743  0.077090  0.108661  0.024088  483.580688   151.0      146.0   23.0
399745  0.093049  0.120275  0.051710  476.024963   106.0      101.0   27.0
399747  0.081545  0.095263  0.036036  451.144684   190.0      190.0   17.0
399749  0.065601  0.091784  0.018511  482.701050   161.0      163.0   17.0
399751  0.081648  0.105500  0.071809  480.361389   232.0      214.0   14.0
399753  0.066593  0.088550  0.051853  526.581848   229.0      238.0   25.0
399755  0.072825  0.101636  0.094258  578.276367   164.0      164.0   20.0
399757  0.065887  0.095937  0.052477  548.708740   132.0      132.0   21.0
399759  0.069659  0.101093  0.030207  555.676392   181.0      182.0   21.0
399761  0.070735  0.109357  0.058723  550.250732   146.0      146.0   20.0
399763  0.072365  0.107858  0.089197  561.311707   139.0      154.0   13.0
399765  0.056592  0.081415  0.051545  540.555481   160.0      156.0   23.0
399767  0.064967  0.085607  0.089106  550.672119   145.0      150.0   17.0
399769  0.061776  0.078614  0.091569  556.899109   132.0      135.0   20.0
399771  0.062326  0.082550  0.085155  528.398499    64.0      129.0   19.0
399773  0.068009  0.070597  0.114776  517.092163    50.0      143.0   16.0
399775  0.068241  0.074682  0.108977  477.597565    73.0      125.0   19.0
399777  0.072452  0.082776  0.136833  463.450500    32.0      154.0   16.0
399779  0.067310  0.080699  0.117430  452.647339   334.0      199.0   14.0
399781  0.050023  0.068132  0.121238  457.049438   307.0      223.0   17.0
399783  0.054246  0.069106  0.139608  510.520569   356.0      182.0    9.0
399785  0.057859  0.073337  0.129649  485.687988    70.0       96.0   30.0
399787  0.065719  0.081182  0.127692  437.638397    87.0      111.0   23.0
399789  0.055749  0.071895  0.129563  433.292572   276.0      215.0   11.0
399791  0.063075  0.083869  0.133273  408.675415    30.0      162.0   12.0
399793  0.070392  0.083507  0.123019  397.970215    64.0      171.0    3.0
399795  0.077075  0.093085  0.116376  397.408936   145.0      175.0    3.0
399797  0.073373  0.093075  0.098073  392.577576   119.0      175.0    2.0
399799  0.069322  0.093969  0.077010  400.975006   176.0      177.0   15.0
399801  0.076639  0.103345  0.082025  397.170776   195.0      183.0    4.0
399803  0.082850  0.107564  0.060859  406.464081   245.0      215.0   12.0
399805  0.087491  0.118863  0.045370  416.255371   156.0      166.0   11.0
399807  0.119419  0.139296  0.094761  402.970337   236.0      204.0    9.0
399809  0.091726  0.133293  0.056795  414.098999   202.0      191.0    9.0
399811  0.091698  0.139086  0.035613  404.692566   111.0      143.0   13.0
399813  0.135736  0.163387  0.081264  398.115143   128.0      168.0    5.0
399815  0.138765  0.179484  0.110587  406.238708   177.0      179.0    5.0
399817  0.115776  0.151755  0.060739  406.287537   294.0      202.0    8.0
399819  0.086772  0.135182  0.019172  423.494232   288.0      201.0    7.0
399821  0.091292  0.141728  0.023505  425.994293    70.0      167.0    5.0
399823  0.095561  0.146036  0.014681  411.928833   212.0      188.0    5.0
399825  0.091049  0.141541  0.028387  421.159607   226.0      199.0    8.0
399827  0.086726  0.144678  0.005885  419.477173   217.0      195.0    8.0
399829  0.099427  0.163616  0.043944  410.539581   144.0      169.0    6.0
399831  0.086916  0.150799  0.050223  423.967957   206.0      198.0   13.0
399833  0.077280  0.110266 -0.012282  427.880859   233.0      227.0   19.0
399835  0.109118  0.142097  0.023773  463.267181    66.0      138.0   15.0
399837  0.090783  0.134333 -0.002977  414.568573    73.0      134.0   16.0
399839  0.095160  0.134229  0.010174  403.829956    72.0      150.0   10.0
399841  0.099205  0.152940  0.043809  389.518768    91.0      167.0    4.0
399843  0.091312  0.148668  0.014696  387.478455    72.0      177.0    1.0
399845  0.095049  0.140719  0.040140  383.648254   215.0      181.0    0.0
399847  0.103235  0.134722  0.070933  381.230194   102.0      173.0    2.0
399849  0.095075  0.141821  0.071487  379.955383   180.0      180.0    8.0

               bi        erc       eto      fm100     fm1000   pr       rmax  \
399743  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399745  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399747  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399749  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399751  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399753  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399755  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399757  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399759  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399761  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399763  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399765  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399767  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399769  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399771  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399773  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399775  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399777  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399779  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399781  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399783  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399785  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399787  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399789  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399791  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399793  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399795  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399797  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399799  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399801  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399803  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399805  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399807  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399809  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399811  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399813  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399815  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399817  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399819  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399821  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399823  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399825  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399827  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399829  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399831  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399833  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399835  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399837  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399839  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399841  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399843  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399845  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399847  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399849  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609

             rmin         th  pop_density        tmmn        tmmx       vpd  \
399743  19.449409 -95.998169     1.758400  293.122375  313.433289  3.423628
399745  19.449409 -95.998169     1.758400  293.122375  313.433289  3.423628
399747  19.449409 -95.998169     1.758400  293.122375  313.433289  3.423628
399749  19.449409 -95.998169     1.758400  293.122375  313.433289  3.423628
399751  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399753  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399755  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399757  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399759  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399761  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399763  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399765  19.449409 -95.998169     9.536811  293.122375  313.433289  3.423628
399767  19.449409 -95.998169     9.536811  293.122375  313.433289  3.423628
399769  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399771  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399773  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399775  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399777  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399779  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399781  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399783  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399785  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399787  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399789  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399791  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399793  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399795  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399797  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399799  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399801  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399803  19.449409 -95.998169   922.347290  293.122375  313.433289  3.423628
399805  19.449409 -95.998169   244.754898  293.122375  313.433289  3.423628
399807  19.449409 -95.998169   244.754898  293.122375  313.433289  3.423628
399809  19.449409 -95.998169   244.754898  293.122375  313.433289  3.423628
399811  18.735531 -95.998169   244.754898  291.830811  314.164154  3.514813
399813  18.735531 -95.998169   244.754898  291.830811  314.164154  3.514813
399815  18.735531 -95.998169   244.754898  291.830811  314.164154  3.514813
399817  18.735531 -95.998169   244.754898  291.830811  314.164154  3.514813
399819  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399821  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399823  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399825  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399827  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399829  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399831  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399833  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399835  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399837  18.735531 -95.998169    10.145011  291.830811  314.164154  3.514813
399839  18.735531 -95.998169    10.145011  291.830811  314.164154  3.514813
399841  18.735531 -95.998169    10.145011  291.830811  314.164154  3.514813
399843  18.735531 -95.998169    10.145011  291.830811  314.164154  3.514813
399845  18.735531 -95.998169   249.957687  291.830811  314.164154  3.514813
399847  18.735531 -95.998169   249.957687  291.830811  314.164154  3.514813
399849  18.735531 -95.998169   249.957687  291.830811  314.164154  3.514813

              vs  Y  Water  Very_low_rural  Low_density_rural  Rural_cluster  \
399743  1.843859  1      0               1                  0              0
399745  1.843859  1      0               1                  0              0
399747  1.843859  1      0               1                  0              0
399749  1.843859  1      0               1                  0              0
399751  1.843859  1      0               1                  0              0
399753  1.843859  1      0               1                  0              0
399755  1.843859  1      0               1                  0              0
399757  1.843859  1      0               1                  0              0
399759  1.843859  1      0               1                  0              0
399761  1.843859  1      0               1                  0              0
399763  1.843859  1      0               1                  0              0
399765  1.843859  1      0               1                  0              0
399767  1.843859  1      0               1                  0              0
399769  1.843859  1      0               1                  0              0
399771  1.843859  1      0               1                  0              0
399773  1.843859  1      0               1                  0              0
399775  1.843859  1      0               1                  0              0
399777  1.843859  1      0               1                  0              0
399779  1.843859  1      0               1                  0              0
399781  1.843859  1      0               0                  1              0
399783  1.843859  1      0               0                  1              0
399785  1.843859  1      0               0                  1              0
399787  1.843859  1      0               0                  1              0
399789  1.843859  1      0               0                  1              0
399791  1.843859  1      0               0                  1              0
399793  1.843859  1      0               0                  1              0
399795  1.843859  1      0               0                  1              0
399797  1.843859  1      0               0                  0              1
399799  1.843859  1      0               0                  0              1
399801  1.843859  1      0               0                  1              0
399803  1.843859  1      0               0                  1              0
399805  1.843859  1      0               0                  1              0
399807  1.843859  1      0               0                  1              0
399809  1.843859  1      0               0                  1              0
399811  2.044341  1      0               0                  1              0
399813  2.044341  1      0               0                  1              0
399815  2.044341  1      0               0                  1              0
399817  2.044341  1      0               0                  1              0
399819  2.044341  1      0               0                  1              0
399821  2.044341  1      0               0                  1              0
399823  2.044341  1      0               0                  1              0
399825  2.044341  1      0               0                  1              0
399827  2.044341  1      0               0                  1              0
399829  2.044341  1      0               0                  1              0

In [ ]:
X_train[0].columns

Index(['FIRE_ID', 'UrbanAngle', 'occur_id', 'point_id', 'IsUrban', 'NDVI',
       'NDWI', 'NBR', 'DEM', 'aspect', 'hillshade', 'slope', 'bi', 'erc',
       'eto', 'fm100', 'fm1000', 'pr', 'rmax', 'rmin', 'th', 'pop_density',
       'tmmn', 'tmmx', 'vpd', 'vs', 'Y', 'Water', 'Very_low_rural',
       'Low_density_rural', 'Rural_cluster', 'Suburban', 'Semi_dense_urban',
       'Dense_urban', 'Urban_centre'],
      dtype='object')

In [ ]:
X_scaler = train_scaler(X_train)

                      FIRE_ID  UrbanAngle  occur_id  point_id  IsUrban  \
399743  CA3443711869619880903   62.778349      3521         1        0
399745  CA3443711869619880903   62.778349      3521         3        0
399747  CA3443711869619880903   62.778349      3521         5        0
399749  CA3443711869619880903   62.778349      3521         7        0
399751  CA3443711869619880903   62.778349      3521         9        0
399753  CA3443711869619880903   62.778349      3521        11        0
399755  CA3443711869619880903   62.778349      3521        13        0
399757  CA3443711869619880903   62.778349      3521        15        0
399759  CA3443711869619880903   62.778349      3521        17        0
399761  CA3443711869619880903   62.778349      3521        19        0
399763  CA3443711869619880903   62.778349      3521        21        0
399765  CA3443711869619880903   62.778349      3521        23        0
399767  CA3443711869619880903   62.778349      3521        25        0
399769  CA3443711869619880903   62.778349      3521        27        0
399771  CA3443711869619880903   62.778349      3521        29        0
399773  CA3443711869619880903   62.778349      3521        31        0
399775  CA3443711869619880903   62.778349      3521        33        0
399777  CA3443711869619880903   62.778349      3521        35        0
399779  CA3443711869619880903   62.778349      3521        37        0
399781  CA3443711869619880903   62.778349      3521        39        0
399783  CA3443711869619880903   62.778349      3521        41        0
399785  CA3443711869619880903   62.778349      3521        43        0
399787  CA3443711869619880903   62.778349      3521        45        0
399789  CA3443711869619880903   62.778349      3521        47        0
399791  CA3443711869619880903   62.778349      3521        49        0
399793  CA3443711869619880903   62.778349      3521        51        1
399795  CA3443711869619880903   62.778349      3521        53        1
399797  CA3443711869619880903   62.778349      3521        55        0
399799  CA3443711869619880903   62.778349      3521        57        0
399801  CA3443711869619880903   62.778349      3521        59        0
399803  CA3443711869619880903   62.778349      3521        61        0
399805  CA3443711869619880903   62.778349      3521        63        0
399807  CA3443711869619880903   62.778349      3521        65        0
399809  CA3443711869619880903   62.778349      3521        67        0
399811  CA3443711869619880903   62.778349      3521        69        0
399813  CA3443711869619880903   62.778349      3521        71        1
399815  CA3443711869619880903   62.778349      3521        73        0
399817  CA3443711869619880903   62.778349      3521        75        0
399819  CA3443711869619880903   62.778349      3521        77        0
399821  CA3443711869619880903   62.778349      3521        79        0
399823  CA3443711869619880903   62.778349      3521        81        0
399825  CA3443711869619880903   62.778349      3521        83        0
399827  CA3443711869619880903   62.778349      3521        85        0
399829  CA3443711869619880903   62.778349      3521        87        0
399831  CA3443711869619880903   62.778349      3521        89        0
399833  CA3443711869619880903   62.778349      3521        91        0
399835  CA3443711869619880903   62.778349      3521        93        0
399837  CA3443711869619880903   62.778349      3521        95        0
399839  CA3443711869619880903   62.778349      3521        97        0
399841  CA3443711869619880903   62.778349      3521        99        0
399843  CA3443711869619880903   62.778349      3521       101        0
399845  CA3443711869619880903   62.778349      3521       103        1
399847  CA3443711869619880903   62.778349      3521       105        1
399849  CA3443711869619880903   62.778349      3521       107        1

            NDVI      NDWI       NBR         DEM  aspect  hillshade  slope  \
399743  0.077090  0.108661  0.024088  483.580688   151.0      146.0   23.0
399745  0.093049  0.120275  0.051710  476.024963   106.0      101.0   27.0
399747  0.081545  0.095263  0.036036  451.144684   190.0      190.0   17.0
399749  0.065601  0.091784  0.018511  482.701050   161.0      163.0   17.0
399751  0.081648  0.105500  0.071809  480.361389   232.0      214.0   14.0
399753  0.066593  0.088550  0.051853  526.581848   229.0      238.0   25.0
399755  0.072825  0.101636  0.094258  578.276367   164.0      164.0   20.0
399757  0.065887  0.095937  0.052477  548.708740   132.0      132.0   21.0
399759  0.069659  0.101093  0.030207  555.676392   181.0      182.0   21.0
399761  0.070735  0.109357  0.058723  550.250732   146.0      146.0   20.0
399763  0.072365  0.107858  0.089197  561.311707   139.0      154.0   13.0
399765  0.056592  0.081415  0.051545  540.555481   160.0      156.0   23.0
399767  0.064967  0.085607  0.089106  550.672119   145.0      150.0   17.0
399769  0.061776  0.078614  0.091569  556.899109   132.0      135.0   20.0
399771  0.062326  0.082550  0.085155  528.398499    64.0      129.0   19.0
399773  0.068009  0.070597  0.114776  517.092163    50.0      143.0   16.0
399775  0.068241  0.074682  0.108977  477.597565    73.0      125.0   19.0
399777  0.072452  0.082776  0.136833  463.450500    32.0      154.0   16.0
399779  0.067310  0.080699  0.117430  452.647339   334.0      199.0   14.0
399781  0.050023  0.068132  0.121238  457.049438   307.0      223.0   17.0
399783  0.054246  0.069106  0.139608  510.520569   356.0      182.0    9.0
399785  0.057859  0.073337  0.129649  485.687988    70.0       96.0   30.0
399787  0.065719  0.081182  0.127692  437.638397    87.0      111.0   23.0
399789  0.055749  0.071895  0.129563  433.292572   276.0      215.0   11.0
399791  0.063075  0.083869  0.133273  408.675415    30.0      162.0   12.0
399793  0.070392  0.083507  0.123019  397.970215    64.0      171.0    3.0
399795  0.077075  0.093085  0.116376  397.408936   145.0      175.0    3.0
399797  0.073373  0.093075  0.098073  392.577576   119.0      175.0    2.0
399799  0.069322  0.093969  0.077010  400.975006   176.0      177.0   15.0
399801  0.076639  0.103345  0.082025  397.170776   195.0      183.0    4.0
399803  0.082850  0.107564  0.060859  406.464081   245.0      215.0   12.0
399805  0.087491  0.118863  0.045370  416.255371   156.0      166.0   11.0
399807  0.119419  0.139296  0.094761  402.970337   236.0      204.0    9.0
399809  0.091726  0.133293  0.056795  414.098999   202.0      191.0    9.0
399811  0.091698  0.139086  0.035613  404.692566   111.0      143.0   13.0
399813  0.135736  0.163387  0.081264  398.115143   128.0      168.0    5.0
399815  0.138765  0.179484  0.110587  406.238708   177.0      179.0    5.0
399817  0.115776  0.151755  0.060739  406.287537   294.0      202.0    8.0
399819  0.086772  0.135182  0.019172  423.494232   288.0      201.0    7.0
399821  0.091292  0.141728  0.023505  425.994293    70.0      167.0    5.0
399823  0.095561  0.146036  0.014681  411.928833   212.0      188.0    5.0
399825  0.091049  0.141541  0.028387  421.159607   226.0      199.0    8.0
399827  0.086726  0.144678  0.005885  419.477173   217.0      195.0    8.0
399829  0.099427  0.163616  0.043944  410.539581   144.0      169.0    6.0
399831  0.086916  0.150799  0.050223  423.967957   206.0      198.0   13.0
399833  0.077280  0.110266 -0.012282  427.880859   233.0      227.0   19.0
399835  0.109118  0.142097  0.023773  463.267181    66.0      138.0   15.0
399837  0.090783  0.134333 -0.002977  414.568573    73.0      134.0   16.0
399839  0.095160  0.134229  0.010174  403.829956    72.0      150.0   10.0
399841  0.099205  0.152940  0.043809  389.518768    91.0      167.0    4.0
399843  0.091312  0.148668  0.014696  387.478455    72.0      177.0    1.0
399845  0.095049  0.140719  0.040140  383.648254   215.0      181.0    0.0
399847  0.103235  0.134722  0.070933  381.230194   102.0      173.0    2.0
399849  0.095075  0.141821  0.071487  379.955383   180.0      180.0    8.0

               bi        erc       eto      fm100     fm1000   pr       rmax  \
399743  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399745  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399747  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399749  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399751  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399753  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399755  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399757  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399759  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399761  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399763  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399765  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399767  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399769  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399771  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399773  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399775  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399777  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399779  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399781  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399783  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399785  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399787  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399789  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399791  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399793  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399795  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399797  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399799  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399801  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399803  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399805  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399807  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399809  36.474396  53.903961  6.201510  11.077076  12.214832  0.0  68.463531
399811  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399813  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399815  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399817  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399819  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399821  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399823  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399825  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399827  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399829  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399831  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399833  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399835  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399837  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399839  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399841  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399843  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399845  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399847  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609
399849  36.710377  52.201000  6.521551  11.654501  12.521743  0.0  74.920609

             rmin         th  pop_density        tmmn        tmmx       vpd  \
399743  19.449409 -95.998169     1.758400  293.122375  313.433289  3.423628
399745  19.449409 -95.998169     1.758400  293.122375  313.433289  3.423628
399747  19.449409 -95.998169     1.758400  293.122375  313.433289  3.423628
399749  19.449409 -95.998169     1.758400  293.122375  313.433289  3.423628
399751  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399753  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399755  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399757  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399759  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399761  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399763  19.449409 -95.998169     5.180637  293.122375  313.433289  3.423628
399765  19.449409 -95.998169     9.536811  293.122375  313.433289  3.423628
399767  19.449409 -95.998169     9.536811  293.122375  313.433289  3.423628
399769  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399771  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399773  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399775  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399777  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399779  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399781  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399783  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399785  19.449409 -95.998169   123.933601  293.122375  313.433289  3.423628
399787  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399789  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399791  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399793  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399795  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399797  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399799  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399801  19.449409 -95.998169   393.390900  293.122375  313.433289  3.423628
399803  19.449409 -95.998169   922.347290  293.122375  313.433289  3.423628
399805  19.449409 -95.998169   244.754898  293.122375  313.433289  3.423628
399807  19.449409 -95.998169   244.754898  293.122375  313.433289  3.423628
399809  19.449409 -95.998169   244.754898  293.122375  313.433289  3.423628
399811  18.735531 -95.998169   244.754898  291.830811  314.164154  3.514813
399813  18.735531 -95.998169   244.754898  291.830811  314.164154  3.514813
399815  18.735531 -95.998169   244.754898  291.830811  314.164154  3.514813
399817  18.735531 -95.998169   244.754898  291.830811  314.164154  3.514813
399819  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399821  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399823  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399825  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399827  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399829  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399831  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399833  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399835  18.735531 -95.998169    66.837341  291.830811  314.164154  3.514813
399837  18.735531 -95.998169    10.145011  291.830811  314.164154  3.514813
399839  18.735531 -95.998169    10.145011  291.830811  314.164154  3.514813
399841  18.735531 -95.998169    10.145011  291.830811  314.164154  3.514813
399843  18.735531 -95.998169    10.145011  291.830811  314.164154  3.514813
399845  18.735531 -95.998169   249.957687  291.830811  314.164154  3.514813
399847  18.735531 -95.998169   249.957687  291.830811  314.164154  3.514813
399849  18.735531 -95.998169   249.957687  291.830811  314.164154  3.514813

              vs  Y  Water  Very_low_rural  Low_density_rural  Rural_cluster  \
399743  1.843859  1      0               1                  0              0
399745  1.843859  1      0               1                  0              0
399747  1.843859  1      0               1                  0              0
399749  1.843859  1      0               1                  0              0
399751  1.843859  1      0               1                  0              0
399753  1.843859  1      0               1                  0              0
399755  1.843859  1      0               1                  0              0
399757  1.843859  1      0               1                  0              0
399759  1.843859  1      0               1                  0              0
399761  1.843859  1      0               1                  0              0
399763  1.843859  1      0               1                  0              0
399765  1.843859  1      0               1                  0              0
399767  1.843859  1      0               1                  0              0
399769  1.843859  1      0               1                  0              0
399771  1.843859  1      0               1                  0              0
399773  1.843859  1      0               1                  0              0
399775  1.843859  1      0               1                  0              0
399777  1.843859  1      0               1                  0              0
399779  1.843859  1      0               1                  0              0
399781  1.843859  1      0               0                  1              0
399783  1.843859  1      0               0                  1              0
399785  1.843859  1      0               0                  1              0
399787  1.843859  1      0               0                  1              0
399789  1.843859  1      0               0                  1              0
399791  1.843859  1      0               0                  1              0
399793  1.843859  1      0               0                  1              0
399795  1.843859  1      0               0                  1              0
399797  1.843859  1      0               0                  0              1
399799  1.843859  1      0               0                  0              1
399801  1.843859  1      0               0                  1              0
399803  1.843859  1      0               0                  1              0
399805  1.843859  1      0               0                  1              0
399807  1.843859  1      0               0                  1              0
399809  1.843859  1      0               0                  1              0
399811  2.044341  1      0               0                  1              0
399813  2.044341  1      0               0                  1              0
399815  2.044341  1      0               0                  1              0
399817  2.044341  1      0               0                  1              0
399819  2.044341  1      0               0                  1              0
399821  2.044341  1      0               0                  1              0
399823  2.044341  1      0               0                  1              0
399825  2.044341  1      0               0                  1              0
399827  2.044341  1      0               0                  1              0
399829  2.044341  1      0               0                  1              0

In [ ]:
import os
from pickle import dump

output_dir = '/content/drive/MyDrive/'
#os.makedirs(output_dir, exist_ok=True)

dump(X_scaler, open(os.path.join(output_dir, 'wildfire_scaler_WUI.keras'), 'wb'))

In [ ]:
X_train = scaler_transform(X_train, X_scaler)

In [ ]:
print(X_train[0].shape)

(54, 30)

In [ ]:
print(X_train[0])

[[ 0.59677807 -0.45425718 -0.40726908 ... -0.06851018 -0.08069557
  -0.13497143]
 [ 0.59677807 -0.32627379 -0.30490184 ... -0.06851018 -0.08069557
  -0.13497143]
 [ 0.59677807 -0.41853115 -0.52534541 ... -0.06851018 -0.08069557
  -0.13497143]
 ...
 [ 0.59677807 -0.31022766 -0.12471519 ... -0.06851018 -0.08069557
  -0.13497143]
 [ 0.59677807 -0.24457923 -0.17757606 ... -0.06851018 -0.08069557
  -0.13497143]
 [ 0.59677807 -0.31002043 -0.11500862 ... -0.06851018 -0.08069557
  -0.13497143]]

In [ ]:
X_padded = sequence.pad_sequences(X_train, padding='post', dtype='float32', value=-9)
Y_padded = sequence.pad_sequences(Y_train, padding='post', dtype='float32', value=-9)

In [ ]:
print(len(X_padded))
print(len(Y_padded))

print(X_padded[0].shape)
print(Y_padded[0].shape)
print(X_padded.shape)
print(Y_padded.shape)

15399
15399
(101, 30)
(101,)
(15399, 101, 30)
(15399, 101)

In [ ]:
def count_Y_values(Ytrue_list):
  zero_count = 0
  one_count = 0
  null_count = 0
  all_counts = 0
  for seq in Ytrue_list:
    for i in seq:
      all_counts += 1
      if i == 0:
        zero_count += 1
      elif i == 1:
        one_count += 1
      elif i == -9:
        null_count += 1
  print(f"Zero Count: {zero_count}")
  print(f"One Count: {one_count}")
  print(f"Null Count: {null_count}")
  print(f"All Count: {all_counts}")
  return zero_count, one_count, null_count, all_counts

In [ ]:
# https://keras.io/examples/structured_data/imbalanced_classification/

counts = count_Y_values(Y_padded)
print(
    "Number of positive samples in training data: {} ({:.2f}% of total)".format(
        counts[1], 100 * float(counts[1]) / counts[3]
    )
)

Zero Count: 704770
One Count: 261898
Null Count: 588631
All Count: 1555299
Number of positive samples in training data: 261898 (16.84% of total)

In [1]:
sample_weight = (Y_padded != -9).astype("float32")
Y_padded2 = np.where(Y_padded == -9, 0, Y_padded).astype("float32")

NameError: name 'Y_padded' is not defined

In [ ]:
model = keras.models.Sequential()
model.add(keras.Input(shape=(steps, X_padded.shape[2])))
model.add(keras.layers.Masking(mask_value=-9))
model.add(LSTM(64, return_sequences=True, kernel_initializer='glorot_uniform'))
model.add(Dropout(0.4))
model.add(LSTM(32, return_sequences=True))
model.add(keras.layers.TimeDistributed(Dense(1, activation='sigmoid')))
# model.add(Dense(1)) : this would predict the final value, in this case the value at the WUI border
model.compile(loss='binary_crossentropy', optimizer=Adam(learning_rate=0.001), metrics=['accuracy','recall'])
model.fit(X_padded, Y_padded2, epochs=50, batch_size=1, verbose=2, sample_weight=sample_weight)

Epoch 1/50
15399/15399 - 284s - 18ms/step - accuracy: 0.8655 - loss: 0.2396 - recall: 0.6774
Epoch 2/50
15399/15399 - 271s - 18ms/step - accuracy: 0.8818 - loss: 0.1773 - recall: 0.7354
Epoch 3/50
15399/15399 - 269s - 17ms/step - accuracy: 0.8876 - loss: 0.1656 - recall: 0.7554
Epoch 4/50
15399/15399 - 338s - 22ms/step - accuracy: 0.8941 - loss: 0.1546 - recall: 0.7733
Epoch 5/50
15399/15399 - 310s - 20ms/step - accuracy: 0.8991 - loss: 0.1472 - recall: 0.7901
Epoch 6/50
15399/15399 - 263s - 17ms/step - accuracy: 0.9039 - loss: 0.1401 - recall: 0.8072
Epoch 7/50
15399/15399 - 319s - 21ms/step - accuracy: 0.9075 - loss: 0.1339 - recall: 0.8189
Epoch 8/50
15399/15399 - 259s - 17ms/step - accuracy: 0.9108 - loss: 0.1289 - recall: 0.8269
Epoch 9/50
15399/15399 - 255s - 17ms/step - accuracy: 0.9128 - loss: 0.1260 - recall: 0.8319
Epoch 10/50
15399/15399 - 259s - 17ms/step - accuracy: 0.9157 - loss: 0.1222 - recall: 0.8406
Epoch 11/50
15399/15399 - 276s - 18ms/step - accuracy: 0.9182 - loss: 0.1187 - recall: 0.8482
Epoch 12/50
15399/15399 - 334s - 22ms/step - accuracy: 0.9202 - loss: 0.1166 - recall: 0.8507
Epoch 13/50
15399/15399 - 259s - 17ms/step - accuracy: 0.9231 - loss: 0.1121 - recall: 0.8597
Epoch 14/50
15399/15399 - 261s - 17ms/step - accuracy: 0.9252 - loss: 0.1091 - recall: 0.8629
Epoch 15/50
15399/15399 - 260s - 17ms/step - accuracy: 0.9262 - loss: 0.1071 - recall: 0.8653
Epoch 16/50
15399/15399 - 261s - 17ms/step - accuracy: 0.9271 - loss: 0.1063 - recall: 0.8664
Epoch 17/50
15399/15399 - 264s - 17ms/step - accuracy: 0.9287 - loss: 0.1040 - recall: 0.8694
Epoch 18/50
15399/15399 - 267s - 17ms/step - accuracy: 0.9305 - loss: 0.1025 - recall: 0.8739
Epoch 19/50
15399/15399 - 318s - 21ms/step - accuracy: 0.9309 - loss: 0.1009 - recall: 0.8728
Epoch 20/50
15399/15399 - 259s - 17ms/step - accuracy: 0.9322 - loss: 0.0990 - recall: 0.8764
Epoch 21/50
15399/15399 - 260s - 17ms/step - accuracy: 0.9327 - loss: 0.0992 - recall: 0.8770
Epoch 22/50
15399/15399 - 258s - 17ms/step - accuracy: 0.9337 - loss: 0.0974 - recall: 0.8807
Epoch 23/50
15399/15399 - 263s - 17ms/step - accuracy: 0.9347 - loss: 0.0963 - recall: 0.8812
Epoch 24/50
15399/15399 - 260s - 17ms/step - accuracy: 0.9354 - loss: 0.0946 - recall: 0.8828
Epoch 25/50
15399/15399 - 258s - 17ms/step - accuracy: 0.9355 - loss: 0.0957 - recall: 0.8821
Epoch 26/50
15399/15399 - 256s - 17ms/step - accuracy: 0.9365 - loss: 0.0940 - recall: 0.8845
Epoch 27/50
15399/15399 - 264s - 17ms/step - accuracy: 0.9375 - loss: 0.0925 - recall: 0.8859
Epoch 28/50
15399/15399 - 281s - 18ms/step - accuracy: 0.9375 - loss: 0.0926 - recall: 0.8862
Epoch 29/50
15399/15399 - 270s - 18ms/step - accuracy: 0.9375 - loss: 0.0924 - recall: 0.8866
Epoch 30/50
15399/15399 - 270s - 18ms/step - accuracy: 0.9383 - loss: 0.0913 - recall: 0.8891
Epoch 31/50
15399/15399 - 268s - 17ms/step - accuracy: 0.9393 - loss: 0.0894 - recall: 0.8906
Epoch 32/50
15399/15399 - 266s - 17ms/step - accuracy: 0.9391 - loss: 0.0901 - recall: 0.8890
Epoch 33/50
15399/15399 - 266s - 17ms/step - accuracy: 0.9391 - loss: 0.0896 - recall: 0.8907
Epoch 34/50
15399/15399 - 266s - 17ms/step - accuracy: 0.9389 - loss: 0.0899 - recall: 0.8892
Epoch 35/50
15399/15399 - 320s - 21ms/step - accuracy: 0.9397 - loss: 0.0894 - recall: 0.8902
Epoch 36/50
15399/15399 - 282s - 18ms/step - accuracy: 0.9402 - loss: 0.0884 - recall: 0.8917
Epoch 37/50
15399/15399 - 286s - 19ms/step - accuracy: 0.9404 - loss: 0.0881 - recall: 0.8902
Epoch 38/50
15399/15399 - 273s - 18ms/step - accuracy: 0.9414 - loss: 0.0873 - recall: 0.8948
Epoch 39/50
15399/15399 - 323s - 21ms/step - accuracy: 0.9407 - loss: 0.0882 - recall: 0.8926
Epoch 40/50
15399/15399 - 272s - 18ms/step - accuracy: 0.9417 - loss: 0.0873 - recall: 0.8929
Epoch 41/50
15399/15399 - 269s - 17ms/step - accuracy: 0.9415 - loss: 0.0869 - recall: 0.8938
Epoch 42/50
15399/15399 - 325s - 21ms/step - accuracy: 0.9417 - loss: 0.0868 - recall: 0.8950
Epoch 43/50
15399/15399 - 269s - 17ms/step - accuracy: 0.9421 - loss: 0.0863 - recall: 0.8950
Epoch 44/50
15399/15399 - 282s - 18ms/step - accuracy: 0.9427 - loss: 0.0855 - recall: 0.8954
Epoch 45/50
15399/15399 - 315s - 20ms/step - accuracy: 0.9422 - loss: 0.0859 - recall: 0.8949
Epoch 46/50
15399/15399 - 269s - 17ms/step - accuracy: 0.9419 - loss: 0.0866 - recall: 0.8930
Epoch 47/50
15399/15399 - 270s - 18ms/step - accuracy: 0.9420 - loss: 0.0863 - recall: 0.8958
Epoch 48/50
15399/15399 - 266s - 17ms/step - accuracy: 0.9426 - loss: 0.0863 - recall: 0.8948
Epoch 49/50
15399/15399 - 274s - 18ms/step - accuracy: 0.9430 - loss: 0.0848 - recall: 0.8980
Epoch 50/50
15399/15399 - 268s - 17ms/step - accuracy: 0.9435 - loss: 0.0841 - recall: 0.8977

In [ ]:
model.save('/content/drive/MyDrive/wildfire_model_WUI_100m.keras')

In [ ]:
import copy
X_test_ref = []
for df in X_test:
  df_ref = df.copy(deep=True)
  X_test_ref.append(df_ref)

len(X_test_ref)

6456

In [ ]:
urb_list = []
for df in X_test_ref:
  X_urb = df["IsUrban"]
  urb_list.append(X_urb)

len(urb_list)

6456

In [ ]:
X_test = scaler_transform(X_test, X_scaler)
X_test_padded = sequence.pad_sequences(X_test, padding='post', dtype='float32', value=-9)
X_test_ref_padded = sequence.pad_sequences(X_test, padding='post', dtype='float32', value=-9)
Y_test_padded = sequence.pad_sequences(Y_test, padding='post', dtype='float32', value=-9)
X_test_IsUrban_padded = sequence.pad_sequences(urb_list, padding='post', dtype='float32', value=-9)

In [ ]:
print(X_test_padded.shape)
print(Y_test_padded.shape)
print(X_test_IsUrban_padded.shape)
print(X_test_ref_padded.shape)

(6456, 101, 30)
(6456, 101)
(6456, 101)
(6456, 101, 30)

In [ ]:
# https://machinelearningmastery.com/multivariate-time-series-forecasting-lstms-keras/

# make a prediction
yhat = model.predict(X_test_padded)
threshold = 0.4

202/202 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step

In [ ]:
y_pred = np.where(yhat > threshold, 1,0).astype(int)
y = Y_test_padded.astype(int)

In [ ]:
y_pred = y_pred.reshape(y_pred.shape[0], y_pred.shape[1])

print(y_pred.shape)
print(y.shape)

(6456, 101)
(6456, 101)

In [ ]:
X_test_IsUrban_padded = X_test_IsUrban_padded.astype(int)
urb = X_test_IsUrban_padded.reshape(X_test_IsUrban_padded.shape[0], X_test_IsUrban_padded.shape[1])
print(urb.shape)

(6456, 101)

In [ ]:
print(y[0])

In [ ]:
print(y_pred[0])

In [ ]:
print(urb[3])

In [ ]:
y_list = []
y_pred_list = []
y_final = []
y_pred_final = []
y_final_lengths = []
y_list_urb = []
y_pred_list_urb = []

for y_seq, y_pred_seq, urb_seq in zip(y, y_pred, urb):
  seq_mask = y_seq != -9
  y_seq = y_seq[seq_mask]
  y_pred_seq = y_pred_seq[seq_mask]
  urb_mask_int = urb_seq[seq_mask]

  y_urb_seq = y_seq[urb_mask_int.astype(bool)]
  y_pred_urb_seq = y_pred_seq[urb_mask_int.astype(bool)]

  if len(y_urb_seq) > 0:
    y_WUI = np.max(y_urb_seq)
    y_WUI_pred = np.max(y_pred_urb_seq)
  else:
    y_WUI = 0
    y_WUI_pred = 0

  y_final.append([y_WUI])
  y_pred_final.append([y_WUI_pred])

  y_list.append(y_seq)
  y_pred_list.append(y_pred_seq)
  y_list_urb.append(y_urb_seq)
  y_pred_list_urb.append(y_pred_urb_seq)

  y_urb_values = y_seq[urb_mask_int.astype(bool)]
  y_pred_urb_values = y_pred_seq[urb_mask_int.astype(bool)]


  if np.any(urb_seq == 1):
    first_urban = np.where(urb_seq == 1)[0][0]
    y_final_lengths.append(first_urban + 1)
  else:
    y_final_lengths.append(-9)

In [ ]:
X_test_output_list = []
for test_df, y_t in zip(X_test_ref, y_pred_list):
  test_df_copy = test_df.copy()
  test_df_copy["Y_predicted"] = y_t
  X_test_output_list.append(test_df_copy)

print(X_test_output_list[0].head())

                     FIRE_ID  UrbanAngle  occur_id  point_id  IsUrban  \
75480  CA3340311726720201224 -177.095042     10584         1        0
75482  CA3340311726720201224 -177.095042     10584         3        0
75484  CA3340311726720201224 -177.095042     10584         5        0
75486  CA3340311726720201224 -177.095042     10584         7        0
75488  CA3340311726720201224 -177.095042     10584         9        0

           NDVI      NDWI       NBR         DEM  aspect  hillshade  slope  \
75480  0.123276  0.154627 -0.002858  229.399902   282.0      223.0   14.0
75482  0.154991  0.171198  0.017687  227.217499   258.0      217.0   12.0
75484  0.165118  0.201804  0.008174  213.764359   203.0      195.0   11.0
75486  0.157125  0.169961  0.033804  199.539124   301.0      221.0   15.0
75488  0.139429  0.150008  0.055723  209.033646   269.0      209.0    9.0

         bi   erc  eto  fm100  fm1000   pr        rmax       rmin    th  \
75480  48.0  55.0  3.5   10.6    11.8  0.0   82.199997  16.600000  84.0
75482  48.0  55.0  3.5   10.6    11.8  0.0   82.199997  16.600000  84.0
75484  48.0  55.0  3.5   10.6    11.8  0.0   82.199997  16.600000  84.0
75486  35.0  38.0  3.2   15.5    15.1  0.0  100.000000  21.200001  83.0
75488  35.0  38.0  3.2   15.5    15.1  0.0  100.000000  21.200001  83.0

       pop_density        tmmn        tmmx   vpd   vs  Y  Water  \
75480          0.0  277.500000  297.000000  1.22  3.7  1      0
75482          0.0  277.500000  297.000000  1.22  3.7  1      0
75484          0.0  277.500000  297.000000  1.22  3.7  1      0
75486          0.0  275.299988  296.600006  1.05  3.7  1      0
75488          0.0  275.299988  296.600006  1.05  3.7  1      0

       Very_low_rural  Low_density_rural  Rural_cluster  Suburban  \
75480               1                  0              0         0
75482               1                  0              0         0
75484               1                  0              0         0
75486               1                  0              0         0
75488               1                  0              0         0

       Semi_dense_urban  Dense_urban  Urban_centre  Y_predicted
75480                 0            0             0            1
75482                 0            0             0            1
75484                 0            0             0            1
75486                 0            0             0            1
75488                 0            0             0            1

In [ ]:
out_df = X_test_output_list[0]
for df in X_test_output_list[1:]:
  out_df = pd.concat([out_df, df])

In [ ]:
len(out_df)

In [ ]:
out_df.to_csv('/content/drive/MyDrive/wildfire_model_df_100m.csv')

In [ ]:
print(y_final_lengths[:100])

In [ ]:
print(y_list[0])
print("\n")
print(y_pred_list[0])

In [ ]:
print(y_list_urb[1])
print("\n")
print(y_pred_list_urb[1])

In [ ]:
print(y_final)
print("\n")
print(y_pred_final)
print("\n")
print(y_final_lengths)

In [ ]:
def calculate_metrics_all_points(ytrue_list, yhat_list, min_length, max_length, Breach=False):
  TP_count = 0
  FP_count = 0
  TN_count = 0
  FN_count = 0
  for y_seq, y_pred_seq in zip(ytrue_list, yhat_list):
    if len(y_seq) > min_length and len(y_seq) <= max_length:
      for i in range(len(y_seq)):
        if y_seq[i] == 1 and y_pred_seq[i] == 1:
          TP_count += 1
        elif y_seq[i] == 0 and y_pred_seq[i] == 1:
          FP_count += 1
        elif y_seq[i] == 1 and y_pred_seq[i] == 0:
          FN_count += 1
        elif y_seq[i] == 0 and y_pred_seq[i] == 0:
          TN_count += 1

    total_rows = TP_count + FP_count + TN_count + FN_count
    try:
      accuracy = round((TP_count + TN_count) / total_rows, 2)
    except:
      accuracy = 0

    # precision tp / (tp + fp)
    try:
      precision = round(TP_count / (TP_count + FP_count),2)
    except:
      precision = 0

    # recall: tp / (tp + fn)
    try:
      recall = round(TP_count / (TP_count + FN_count), 2)
    except:
      recall = 0

    # f1: 2 tp / (2 tp + fp + fn)
    try:
      f1 = round(2 * ((precision * recall)/ (precision + recall)), 2)
    except:
      f1 = 0


    confusion_matrix = [TP_count, FP_count, FN_count, TN_count]


  return accuracy, precision, recall, f1, confusion_matrix

In [ ]:
def test_calculate_metrics_all_points(ytrue_list, yhat_list, min_distance, max_distance, Breach=False):
  TP_count = 0
  FP_count = 0
  TN_count = 0
  FN_count = 0
  for y_seq, y_pred_seq in zip(ytrue_list, yhat_list):
    for i in range(len(y_seq)):
      if i >= min_distance and i < max_distance:
        if y_seq[i] == 1 and y_pred_seq[i] == 1:
          TP_count += 1
        elif y_seq[i] == 0 and y_pred_seq[i] == 1:
          FP_count += 1
        elif y_seq[i] == 1 and y_pred_seq[i] == 0:
          FN_count += 1
        elif y_seq[i] == 0 and y_pred_seq[i] == 0:
          TN_count += 1

    total_rows = TP_count + FP_count + TN_count + FN_count
    try:
      accuracy = round((TP_count + TN_count) / total_rows, 2)
    except:
      accuracy = 0

    # precision tp / (tp + fp)
    try:
      precision = round(TP_count / (TP_count + FP_count),2)
    except:
      precision = 0

    # recall: tp / (tp + fn)
    try:
      recall = round(TP_count / (TP_count + FN_count), 2)
    except:
      recall = 0

    # f1: 2 tp / (2 tp + fp + fn)
    try:
      f1 = round(2 * ((precision * recall)/ (precision + recall)), 2)
    except:
      f1 = 0


    confusion_matrix = [TP_count, FP_count, FN_count, TN_count]


  return accuracy, precision, recall, f1, confusion_matrix

In [ ]:
model_accuracy, model_precision, model_recall, model_f1, model_confusion = calculate_metrics_all_points(y_list, y_pred_list, 0, X_test_padded.shape[0])
print(f"Accuracy: {model_accuracy}")
print(f"Recall: {model_recall}")
print(f"Precision: {model_precision}")
print(f"F1 score: {model_f1}")
print(f"Confusion matrix: {model_confusion}")

Accuracy: 0.83
Recall: 0.79
Precision: 0.67
F1 score: 0.73
Confusion matrix: [88746, 43933, 23074, 246912]

In [ ]:
urban_fire_accuracy, urban_fire_precision, urban_fire_recall, urban_fire_f1, urban_fire_confusion = calculate_metrics_all_points(y_list_urb, y_pred_list_urb, 0, X_test_padded.shape[0])

# this is a fire / non fire prediction, not a WUI breach prediction
# for urban points, did the fire spread there?

print(f"Accuracy (urban fire): {urban_fire_accuracy}")
print(f"Recall (urban fire): {urban_fire_recall}")
print(f"Precision (urban fire): {urban_fire_precision}")
print(f"F1 score (urban fire): {urban_fire_f1}")
print(f"Confusion matrix (urban fire): {urban_fire_confusion}")

Accuracy (urban fire): 0.94
Recall (urban fire): 0.64
Precision (urban fire): 0.38
F1 score (urban fire): 0.48
Confusion matrix (urban fire): [1452, 2359, 832, 45319]

In [ ]:
WUI_breach_accuracy, WUI_breach_precision, WUI_breach_recall, WUI_breach_f1, WUI_breach_confusion = calculate_metrics_all_points(y_final, y_pred_final, 0, X_test_padded.shape[0])

print(f"WUI Breach Accuracy: {WUI_breach_accuracy}")
print(f"WUI Breach Recall: {WUI_breach_recall}")
print(f"WUI Breach Precision: {WUI_breach_precision}")
print(f"WUI Breach F1 score: {WUI_breach_f1}")
print(f"WUI Breach Confusion matrix: {WUI_breach_confusion}")

WUI Breach Accuracy: 0.9
WUI Breach Recall: 0.73
WUI Breach Precision: 0.47
WUI Breach F1 score: 0.57
WUI Breach Confusion matrix: [429, 479, 156, 5392]

In [ ]:
def display_confusion_matrix(confusion_matrix, min_distance, max_distance):
  header = f"{min_distance}km to {max_distance}km"
  c_f = pd.DataFrame(columns=[header, 'True', 'False'])

  new_row_positive = pd.DataFrame([["Positive", confusion_matrix[0], confusion_matrix[1]]], columns=c_f.columns)
  c_f = pd.concat([c_f, new_row_positive], ignore_index =True)

  new_row_negative = pd.DataFrame([["Negative", confusion_matrix[3], confusion_matrix[2]]], columns=c_f.columns)
  c_f = pd.concat([c_f, new_row_negative], ignore_index =True)

  return c_f

In [ ]:
def calculate_metrics_by_distance(ytrue_list, yhat_list, interval):
  min_ = 0
  start_ = 0 + interval
  max_ = start_
  all_cm = []
  all_point_stats = pd.DataFrame(columns=['Min_Kilometres', 'Max_Kilometres', 'Accuracy', 'Precision', 'Recall', 'F1'])
  for max_ in range(start_, 105, interval):
    accuracy, precision, recall, f1, conf = test_calculate_metrics_all_points(ytrue_list, yhat_list, min_, max_)
    new_row = pd.DataFrame([[(min_/10), (max_/10), accuracy, precision, recall, f1]], columns=all_point_stats.columns)
    all_point_stats = pd.concat([all_point_stats, new_row], ignore_index =True)
    conf_matrix = display_confusion_matrix(conf, min_/10, max_/10)
    all_cm.append(conf_matrix)
    min_ += interval
    max_ += interval

  return all_point_stats, all_cm

In [ ]:
def calculate_WUI_breach_metrics_by_distance(ytrue_list, yhat_list, y_length_list, interval):
  min_ = 0
  start_ = 0 + interval
  max_ = start_
  all_cm = []
  all_point_stats = pd.DataFrame(columns=['Min_Kilometres', 'Max_Kilometres', 'Accuracy', 'Precision', 'Recall', 'F1'])

  for max_ in range(start_, 105, interval):
    y_check = []
    y_pred_check = []
    for y, y_pred, y_length in zip(ytrue_list, yhat_list, y_length_list):
      if y_length > min_ and y_length <= max_:
        y_check.append(y)
        y_pred_check.append(y_pred)
    accuracy, precision, recall, f1, conf = test_calculate_metrics_all_points(y_check, y_pred_check, 0, X_test_padded.shape[0])
    new_row = pd.DataFrame([[(min_/10), (max_/10), accuracy, precision, recall, f1]], columns=all_point_stats.columns)
    all_point_stats = pd.concat([all_point_stats, new_row], ignore_index =True)
    conf_matrix = display_confusion_matrix(conf, min_/10, max_/10)
    all_cm.append(conf_matrix)
    min_ += interval
    max_ += interval

  return all_point_stats, all_cm

In [ ]:
distance_stats, distance_cm = calculate_metrics_by_distance(y_list, y_pred_list, 10)

print(distance_stats)
print("\n")
for c in distance_cm:
  print(c)
  print("\n")

/tmp/ipykernel_6971/1875484337.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_point_stats = pd.concat([all_point_stats, new_row], ignore_index =True)

   Min_Kilometres  Max_Kilometres  Accuracy  Precision  Recall    F1
0             0.0             1.0      0.89       0.91    0.97  0.94
1             1.0             2.0      0.63       0.60    0.75  0.67
2             2.0             3.0      0.70       0.34    0.49  0.40
3             3.0             4.0      0.82       0.22    0.32  0.26
4             4.0             5.0      0.91       0.23    0.30  0.26
5             5.0             6.0      0.94       0.27    0.29  0.28
6             6.0             7.0      0.96       0.31    0.29  0.30
7             7.0             8.0      0.98       0.38    0.34  0.36
8             8.0             9.0      0.99       0.47    0.49  0.48
9             9.0            10.0      1.00       1.00    1.00  1.00


  0.0km to 1.0km   True False
0       Positive  56182  5774
1       Negative    670  1570


  1.0km to 2.0km   True  False
0       Positive  23099  15360
1       Negative  15623   7524


  2.0km to 3.0km   True  False
0       Positive   5949  11655
1       Negative  35559   6264


  3.0km to 4.0km   True False
0       Positive   1770  6277
1       Negative  45266  3721


  4.0km to 5.0km   True False
0       Positive    865  2837
1       Negative  49631  2041


  5.0km to 6.0km   True False
0       Positive    453  1252
1       Negative  37528  1087


  6.0km to 7.0km   True False
0       Positive    232   511
1       Negative  26052   569


  7.0km to 8.0km   True False
0       Positive    120   198
1       Negative  19036   234


  8.0km to 9.0km   True False
0       Positive     61    69
1       Negative  12171    64


  9.0km to 10.0km  True False
0        Positive    15     0
1        Negative  5309     0

In [ ]:
breach_distance_stats, breach_distance_cm = calculate_WUI_breach_metrics_by_distance(y_final, y_pred_final, y_final_lengths, 25)

print(breach_distance_stats)
print("\n")
for c in breach_distance_cm:
  print(c)
  print("\n")

   Min_Kilometres  Max_Kilometres  Accuracy  Precision  Recall    F1
0             0.0             2.5      0.72       0.62    0.81  0.70
1             2.5             5.0      0.87       0.12    0.36  0.18
2             5.0             7.5      0.97       0.19    0.42  0.26
3             7.5            10.0      0.99       0.40    0.60  0.48


  0.0km to 2.5km True False
0       Positive  388   239
1       Negative  445    92


  2.5km to 5.0km  True False
0       Positive    27   197
1       Negative  1583    49


  5.0km to 7.5km  True False
0       Positive     8    34
1       Negative  1573    11


  7.5km to 10.0km  True False
0        Positive     6     9
1        Negative  1652     4

/tmp/ipykernel_6971/2785806771.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_point_stats = pd.concat([all_point_stats, new_row], ignore_index =True)

In [ ]:
all_confusion_matrix = display_confusion_matrix(model_confusion, 0, 100)
print(all_confusion_matrix)

  0km to 100km    True  False
0     Positive   88746  43933
1     Negative  246912  23074